In [1]:
import numpy as np
import pandas as pd
from fontTools.pens import recordingPen

# DataFrame
- 행열을 가진 2차원 자료구조
- 여러개의 Series 묶음 자료형

## DataFrame 생성

In [2]:
# dict =-> df생성
data = {"one": [1.0, 2.0, 3.0], "two": [10, 20, 30], "three": 99}

#dict 의 각 iotem이 하나의 Series로 처리됨
df= pd.DataFrame(data)
print(df['one'])
print(df['two'])

0    1.0
1    2.0
2    3.0
Name: one, dtype: float64
0    10
1    20
2    30
Name: two, dtype: int64

In [3]:
# 여러 개의 dict -> dataframe
data = [{
    "a": 10,
    "b": 20,
}, {
    "a": 30,
    "b": 40,
    "c": 50,
}]

# 하나의 dict -> 하나의 레코드, key는 컬럼으로 처리
df = pd.DataFrame(data)
df

    a   b     c
0  10  20   NaN
1  30  40  50.0

In [4]:
#ndarray -> df
arr = np.arange(9).reshape(3,3)
df = pd.DataFrame(arr, columns=["a", "b", "c"], index=['1일','2일','3일'])
df

    a  b  c
1일  0  1  2
2일  3  4  5
3일  6  7  8

In [5]:
#ser -> df
name_ser = pd.Series(['홍길동','이순신','강감찬'])
age_ser = pd.Series([20,25,30])
df = pd.DataFrame({'name':name_ser,'age':age_ser})
df

  name  age
0  홍길동   20
1  이순신   25
2  강감찬   30

In [6]:
# tuple(record) -> dataframe
# 하나의 객체

data = [
    ('홍길동', 20),
    ('이순신', 30),
    ('논개', 43),
]
df = pd.DataFrame.from_records(data, columns=['이름', '나이'])
df

    이름  나이
0  홍길동  20
1  이순신  30
2   논개  43

## DataFrame 속성

In [7]:
data = {
    'Bank client ID':[1, 2, 3, 4],
    'Bank Client Name':['Laila Aly', 'Kate Steve', 'Nicole Mitch', 'Francis Morris'],
    'Net worth [$]':[35000, 3000, 100000, 2000],
    'Years with bank':[4, 7, 10, 15]
}
df = pd.DataFrame(data)
df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0               1        Laila Aly          35000                4
1               2       Kate Steve           3000                7
2               3     Nicole Mitch         100000               10
3               4   Francis Morris           2000               15

In [8]:
# df.info()
print(df.describe())

       Bank client ID  Net worth [$]  Years with bank
count        4.000000       4.000000         4.000000
mean         2.500000   35000.000000         9.000000
std          1.290994   45963.753836         4.690416
min          1.000000    2000.000000         4.000000
25%          1.750000    2750.000000         6.250000
50%          2.500000   19000.000000         8.500000
75%          3.250000   51250.000000        11.250000
max          4.000000  100000.000000        15.000000

In [9]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=4, step=1)
Index(['Bank client ID', 'Bank Client Name', 'Net worth [$]',
       'Years with bank'],
      dtype='str')

In [10]:
print(df.dtypes)
print(df.shape)
print(df.size)

Bank client ID      int64
Bank Client Name      str
Net worth [$]       int64
Years with bank     int64
dtype: object
(4, 4)
16

## DataFrame 메서드

In [11]:
display(df)

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0               1        Laila Aly          35000                4
1               2       Kate Steve           3000                7
2               3     Nicole Mitch         100000               10
3               4   Francis Morris           2000               15

In [12]:
#values_counts() : 유일값 분포 확인
df['Years with bank'].value_counts()

Years with bank
4     1
7     1
10    1
15    1
Name: count, dtype: int64

In [13]:
#index 재지정 : 특정 컬럼을 index로 지정
df = df.set_index('Bank client ID')

In [14]:
df

               Bank Client Name  Net worth [$]  Years with bank
Bank client ID
1                     Laila Aly          35000                4
2                    Kate Steve           3000                7
3                  Nicole Mitch         100000               10
4                Francis Morris           2000               15

## 조회
- 행열조회
    - df.iloc[인덱스]
    - df.loc[라벨]
- 열조회
    - df[컬럼명]

In [15]:
dicts = [
    {'name' : '홍길동', 'job' : '강사', 'age' : 33},
    {'name' : '신사임당', 'age' : 44, 'job' : '영업사원'},
    {'name' : '이순신', 'age' : 38, 'job' : '장군'},
    {'name' : '논개', 'age' : 25, 'job' : '개발'},
    {'name' : '강감찬', 'age' : 47, 'job' : '교수'},
]
df = pd.DataFrame(dicts)
df

   name   job  age
0   홍길동    강사   33
1  신사임당  영업사원   44
2   이순신    장군   38
3    논개    개발   25
4   강감찬    교수   47

In [16]:
#홍길동 행 조회
print(df.iloc[0])
print(type(df.iloc[0])) #Series, df에서 한 행 또는 한 열은  Series 타입이다.
print(df.iloc[0].index)
print(df.iloc[0].name) #  df의 인덱스 == ser의 이름

name    홍길동
job      강사
age      33
Name: 0, dtype: object
<class 'pandas.Series'>
Index(['name', 'job', 'age'], dtype='str')
0

In [17]:
#슬라이싱 지원
df2 = df.iloc[0:2] # 0,1 행 반환
df2

   name   job  age
0   홍길동    강사   33
1  신사임당  영업사원   44

### iloc (인덱스 위치)

In [18]:
# fancy indexing 지원
df.iloc[[0,2]]

  name job  age
0  홍길동  강사   33
2  이순신  장군   38

In [19]:
#단일 값 조회
print(df.iloc[0,1])

# 여러 열 조회
df.iloc[:2,1]

강사

0      강사
1    영업사원
Name: job, dtype: str

In [20]:
df2 = df.iloc[:2,:2]
print(type(df2))
df2

<class 'pandas.DataFrame'>

   name   job
0   홍길동    강사
1  신사임당  영업사원

### loc
인데스라벨을 통해 조회

In [21]:
# index 명 지정 == 라벨링
df.index = ['client1', 'client2', 'client3', 'client4', 'client5']
df

         name   job  age
client1   홍길동    강사   33
client2  신사임당  영업사원   44
client3   이순신    장군   38
client4    논개    개발   25
client5   강감찬    교수   47

In [22]:
print(type(df.loc['client4']))
df.loc['client4']

<class 'pandas.Series'>

name    논개
job     개발
age     25
Name: client4, dtype: object

In [23]:
# df.loc[3] # KeyError

 # loc 슬라이싱은 end값을 포함한다.

In [24]:
 #loc를 이용한 컬럼 단일 값 조회
 df.loc[('client2','job')]

 print( df.loc['client2':'client4'])

 #loc를 이용한 슬라이싱 + 컬럼 선택
 print( df.loc['client2':'client4','job'])

 # job부터 끝까지 ~
 print( df.loc['client2':'client4','job':])

         name   job  age
client2  신사임당  영업사원   44
client3   이순신    장군   38
client4    논개    개발   25
client2    영업사원
client3      장군
client4      개발
Name: job, dtype: str
          job  age
client2  영업사원   44
client3    장군   38
client4    개발   25

### 컬럼라벨

In [25]:
# df['컬럼명] : 해당 컬럼 시리즈 변환
print(type(df['name']))
df['name']

<class 'pandas.Series'>

client1     홍길동
client2    신사임당
client3     이순신
client4      논개
client5     강감찬
Name: name, dtype: str

In [26]:
# column label fancy indexing

print(type(df[['name','job']]))
df[['name','job']]

<class 'pandas.DataFrame'>

         name   job
client1   홍길동    강사
client2  신사임당  영업사원
client3   이순신    장군
client4    논개    개발
client5   강감찬    교수

In [27]:
# loc + 컬럼 라벨
print(df['name']=='이순신')
print(df.loc[df['name']=='이순신'])

client1    False
client2    False
client3     True
client4    False
client5    False
Name: name, dtype: bool
        name job  age
client3  이순신  장군   38

In [28]:
 # boolean indexing(비교 연산)
 print(df['age']>30)
 df[df['age']>30]

client1     True
client2     True
client3     True
client4    False
client5     True
Name: age, dtype: bool

         name   job  age
client1   홍길동    강사   33
client2  신사임당  영업사원   44
client3   이순신    장군   38
client5   강감찬    교수   47

In [29]:
#30세 미만, 개발 직종을 갖는 행 조회
df.loc[ (df['age']<30) & (df['job']=='개발')]

        name job  age
client4   논개  개발   25

In [30]:
# - 이름에 '신'이 들어가거나 나이가 40대이상 조회
df[(df['age'] >= 40) | (df['name'].str.contains('신'))]

         name   job  age
client2  신사임당  영업사원   44
client3   이순신    장군   38
client5   강감찬    교수   47

## 행 추가/삭제

In [31]:
students = [
    {'name': '홍길동', 'midterm': 95, 'final': 85},
    {'name': '신사임당', 'midterm': 85, 'final': 80},
    {'name': '이순신', 'midterm': 10, 'final': 30}
]
df = pd.DataFrame(students)
df

   name  midterm  final
0   홍길동       95     85
1  신사임당       85     80
2   이순신       10     30

In [33]:
#
next_index =3

df.loc[next_index] = pd.Series({'name': '율곡이이', 'midterm': 77})

df

   name  midterm  final
0   홍길동       95   85.0
1  신사임당       85   80.0
2   이순신       10   30.0
3  율곡이이       77    NaN

## 컬럼 추가/삭제

In [37]:
# 행 삭제 # 원본 유지
# df.drop(3)
display(df.drop(3))
display(df)
# 진짜 지우고 ㅣㅍ으면?
df= df.drop(3)

   name  midterm  final
0   홍길동       95   85.0
1  신사임당       85   80.0
2   이순신       10   30.0

   name  midterm  final
0   홍길동       95   85.0
1  신사임당       85   80.0
2   이순신       10   30.0
3  율곡이이       77    NaN

In [50]:
# 특정 조건을 만족하는 모든 행 삭제
df = df[df['final'] > 60] # 60점 이상만 남기기 == 60점 미만 삭제

In [52]:
df['phone'] = ['010-1234-5678','010-11111-2323']
df

   name  midterm  final           phone  mean
0   홍길동       95   85.0   010-1234-5678  90.0
1  신사임당       85   80.0  010-11111-2323  82.5

In [53]:
# 중간고사, 기말고사 평균 컬럼(mean)을 추가
df.loc[:,'mean'] = (df['midterm']+df['final']) / 2
df

   name  midterm  final           phone  mean
0   홍길동       95   85.0   010-1234-5678  90.0
1  신사임당       85   80.0  010-11111-2323  82.5

In [58]:
# 컬럼 삭제

df[['name','midterm','final']] # fancy indexing

   name  midterm  final
0   홍길동       95   85.0
1  신사임당       85   80.0

In [63]:
df.loc[2] = {'name': '이순신', 'midterm': 10, 'final': 30}

In [67]:
# df.apply(함수)
# - 데이터프레임 또는 시리즈 객체의 각 요소에 함수를 적용할 때 사용
# 데이터 전처리 시 자주 사용
def pass_or_fail(value) :
    return 'P' if value >= 60 else 'F'

df.loc[:,'avg'] = (df['midterm']+df['final'])/2
df['avg'].apply(pass_or_fail)
df

   name  midterm  final           phone  mean   avg
0   홍길동       95   85.0   010-1234-5678  90.0  90.0
1  신사임당       85   80.0  010-11111-2323  82.5  82.5
2   이순신       10   30.0             NaN   NaN  20.0

In [73]:
# apply 함수에 행(record) 전체를 인자로 전달해서 처리하기
def pass_or_fail2(record) :
    avg = (record['midterm']+record['final']) /2
    return 'P' if avg >= 60 else 'F'

df.loc[:,'pass_fail2'] = df.apply(pass_or_fail2,axis=1)
df

   name  midterm  final           phone  mean   avg pass_daili2 pass_fail2
0   홍길동       95   85.0   010-1234-5678  90.0  90.0           P          P
1  신사임당       85   80.0  010-11111-2323  82.5  82.5           P          P
2   이순신       10   30.0             NaN   NaN  20.0           F          F

## 정렬

In [83]:
df = pd.read_csv('./data/bank_client_information.csv')
df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [84]:
#지정된 컬럼 기준으로 내림차순
df.sort_values('Net Worth',ascending=False)

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1

In [85]:
# 메인 정렬 중 같은 값이 존재하면ㅁ 추가로 정렬 지정
df.sort_values(['Net Worth','Years with Bank'],ascending=[True,False])

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26

In [86]:
#순위 부여하기
df.loc[:,'Net Worth Rank'] = df['Net Worth'].rank(ascending=False).astype(int)
df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank,Net Worth Rank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5,8
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6,5
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7,6
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10,4
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22,8
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26,1
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11,2
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1,10
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13,7